### ISSUE TITLE
SPIKE: Research go tmpl inheritance

### ISSUE THREAD

**Issue by jpogran** [puppetlabs/pdkgo#106]
Research can we have multiple template inheritance with duplicate defines and duplicate configuration keys. Will the 'last' one read win? Will we have to namespace the configuration keys? Timebox two days. Requires documentation as result of this research.

```
  layouts:
    - puppetlabs/puppet-language@0.1.0
    - jpogran/puppet-language@0.1.0

# pct-config.yml
  puppetlabs.puppet_module:
    license: "Apache 2.0"

  jpogran.puppet_module:
    license: "MIT"
```
