### ISSUE TITLE
Display PCT Configuration to a user

### ISSUE THREAD

**Issue by jpogran** [puppetlabs/pdkgo#43]
As a Content User I would like to see what configuration options for a given template. This would be useful before deploying a template and after.

For example with a `puppet-module` template that provides the following configuration options:

```yaml
---
template:
  id: puppet-module
  type: project
  display: Puppet Module
  version: 0.1.0
  url: https://github.com/puppetlabs/pct-puppet-module

puppet_module:
  license: "Apache-2.0"
  version: "0.1.0"
  summary: "A New Puppet Module"
  operatingsystem_support:
    - operatingsystem: "windows"
      release: [2019, 10]
```

It should display on the command line:

```
> pct new -l puppet-module
DisplayName:     Puppet Module
Name:            puppet-module
TemplateType:    project
TemplateURL:     https://github.com/puppetlabs/pct-puppet-module
TemplateVersion: 0.1.0

Data:
  puppet_module:
    license: "Apache-2.0"
    version: "0.1.0"
    summary: "A New Puppet Module"
    operatingsystem_support:
      - operatingsystem: "windows"
        release: [2019, 10]

```

It should also include the default built-in data points like version information, user, etc.
